export const categories = ['All', 'Cardio', 'Strength', 'Yoga', 'HIIT'] as const

export interface WorkoutItem {
  id: string
  title: string
  category: string
  durationMinutes: number
  duration: string
  calories: string
  difficulty: string
  difficultyColor: string
  imageGradient: string
  description: string
  muscles: string[]
  equipment: string[]
  videoUrl?: string
}

export const workouts: WorkoutItem[] = [
  {
    id: 'hiit-blast',
    title: 'Morning HIIT Blast',
    category: 'HIIT',
    durationMinutes: 20,
    duration: '20 min',
    calories: '240 cal',
    difficulty: 'High',
    difficultyColor: 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400',
    imageGradient: 'from-orange-400 to-pink-500',
    description:
      'Jumpstart your metabolism with this high-intensity interval training session. Alternate between bursts of intense activity and short recovery periods.',
    muscles: ['Legs', 'Core', 'Cardio'],
    equipment: ['Mat', 'Dumbbells (Optional)'],
  },
  {
    id: 'full-body-power',
    title: 'Full Body Power',
    category: 'Strength',
    durationMinutes: 45,
    duration: '45 min',
    calories: '320 cal',
    difficulty: 'Medium',
    difficultyColor: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400',
    imageGradient: 'from-blue-400 to-indigo-500',
    description:
      'Build strength and endurance with this comprehensive full-body routine. Focus on form and controlled movements for maximum benefit.',
    muscles: ['Arms', 'Chest', 'Back', 'Legs'],
    equipment: ['Dumbbells', 'Bench'],
  },
  {
    id: 'sunrise-yoga',
    title: 'Sunrise Yoga Flow',
    category: 'Yoga',
    durationMinutes: 30,
    duration: '30 min',
    calories: '150 cal',
    difficulty: 'Easy',
    difficultyColor: 'text-green-600 bg-green-50 dark:bg-green-900/20 dark:text-green-400',
    imageGradient: 'from-teal-400 to-emerald-500',
    description:
      'Greet the day with a gentle flow designed to wake up your body and center your mind. Perfect for all levels.',
    muscles: ['Core', 'Flexibility', 'Balance'],
    equipment: ['Yoga Mat'],
  },
  {
    id: 'core-crusher',
    title: 'Core Crusher',
    category: 'Strength',
    durationMinutes: 15,
    duration: '15 min',
    calories: '120 cal',
    difficulty: 'Medium',
    difficultyColor: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400',
    imageGradient: 'from-purple-400 to-fuchsia-500',
    description:
      'Target your abs and obliques with this focused core workout. Strengthen your midsection and improve stability.',
    muscles: ['Abs', 'Obliques', 'Lower Back'],
    equipment: ['Mat'],
  },
  {
    id: 'endurance-run',
    title: 'Endurance Run',
    category: 'Cardio',
    durationMinutes: 40,
    duration: '40 min',
    calories: '450 cal',
    difficulty: 'High',
    difficultyColor: 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400',
    imageGradient: 'from-red-400 to-orange-500',
    description:
      'Build cardiovascular endurance with this steady-state run. Maintain a consistent pace and focus on breathing.',
    muscles: ['Legs', 'Heart', 'Lungs'],
    equipment: ['Running Shoes'],
  },
  {
    id: 'evening-stretch',
    title: 'Evening Stretch',
    category: 'Yoga',
    durationMinutes: 10,
    duration: '10 min',
    calories: '50 cal',
    difficulty: 'Easy',
    difficultyColor: 'text-green-600 bg-green-50 dark:bg-green-900/20 dark:text-green-400',
    imageGradient: 'from-indigo-400 to-purple-500',
    description:
      'Wind down before bed with these relaxing stretches. Release tension and prepare your body for restful sleep.',
    muscles: ['Full Body', 'Flexibility'],
    equipment: ['Mat'],
  },
  {
    id: 'push-pull-legs',
    title: 'Push Pull Legs',
    category: 'Strength',
    durationMinutes: 50,
    duration: '50 min',
    calories: '380 cal',
    difficulty: 'High',
    difficultyColor: 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400',
    imageGradient: 'from-amber-400 to-orange-600',
    description: 'Classic PPL split targeting push, pull and leg movements. Ideal for building muscle.',
    muscles: ['Chest', 'Back', 'Legs', 'Shoulders'],
    equipment: ['Dumbbells', 'Barbell', 'Cable Machine'],
  },
  {
    id: 'tabata-sprint',
    title: 'Tabata Sprint',
    category: 'HIIT',
    durationMinutes: 15,
    duration: '15 min',
    calories: '180 cal',
    difficulty: 'High',
    difficultyColor: 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400',
    imageGradient: 'from-rose-400 to-red-500',
    description: '20 seconds max effort, 10 seconds rest. Eight rounds of all-out intensity.',
    muscles: ['Full Body', 'Cardio'],
    equipment: ['Mat', 'Timer'],
  },
  {
    id: 'power-yoga',
    title: 'Power Yoga',
    category: 'Yoga',
    durationMinutes: 45,
    duration: '45 min',
    calories: '220 cal',
    difficulty: 'Medium',
    difficultyColor: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400',
    imageGradient: 'from-emerald-400 to-teal-600',
    description: 'Strong, flowing sequences to build heat, strength and flexibility.',
    muscles: ['Core', 'Arms', 'Legs', 'Balance'],
    equipment: ['Yoga Mat'],
  },
  {
    id: 'cycling-intervals',
    title: 'Cycling Intervals',
    category: 'Cardio',
    durationMinutes: 35,
    duration: '35 min',
    calories: '400 cal',
    difficulty: 'Medium',
    difficultyColor: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400',
    imageGradient: 'from-cyan-400 to-blue-600',
    description: 'Indoor cycling with alternating high and low resistance intervals.',
    muscles: ['Legs', 'Cardio'],
    equipment: ['Stationary Bike'],
  },
  {
    id: 'upper-body-blast',
    title: 'Upper Body Blast',
    category: 'Strength',
    durationMinutes: 25,
    duration: '25 min',
    calories: '200 cal',
    difficulty: 'Medium',
    difficultyColor: 'text-yellow-600 bg-yellow-50 dark:bg-yellow-900/20 dark:text-yellow-400',
    imageGradient: 'from-violet-400 to-purple-600',
    description: 'Focused workout for chest, back, shoulders and arms.',
    muscles: ['Chest', 'Back', 'Shoulders', 'Arms'],
    equipment: ['Dumbbells', 'Resistance Bands'],
  },
  {
    id: 'quick-cardio',
    title: 'Quick Cardio Burn',
    category: 'Cardio',
    durationMinutes: 12,
    duration: '12 min',
    calories: '120 cal',
    difficulty: 'Easy',
    difficultyColor: 'text-green-600 bg-green-50 dark:bg-green-900/20 dark:text-green-400',
    imageGradient: 'from-lime-400 to-green-600',
    description: 'Short burst of cardio to get your heart rate up and burn calories.',
    muscles: ['Legs', 'Cardio'],
    equipment: ['None'],
  },
  {
    id: 'restorative-yoga',
    title: 'Restorative Yoga',
    category: 'Yoga',
    durationMinutes: 20,
    duration: '20 min',
    calories: '80 cal',
    difficulty: 'Easy',
    difficultyColor: 'text-green-600 bg-green-50 dark:bg-green-900/20 dark:text-green-400',
    imageGradient: 'from-slate-400 to-indigo-600',
    description: 'Gentle poses held longer to release tension and restore the body.',
    muscles: ['Full Body', 'Flexibility'],
    equipment: ['Yoga Mat', 'Bolster'],
  },
  {
    id: 'kettlebell-flow',
    title: 'Kettlebell Flow',
    category: 'Strength',
    durationMinutes: 30,
    duration: '30 min',
    calories: '280 cal',
    difficulty: 'High',
    difficultyColor: 'text-red-500 bg-red-50 dark:bg-red-900/20 dark:text-red-400',
    imageGradient: 'from-orange-500 to-amber-600',
    description: 'Dynamic kettlebell movements for strength and conditioning.',
    muscles: ['Legs', 'Core', 'Shoulders'],
    equipment: ['Kettlebell'],
  },
]
